### PR TITLE
contents/people: Add Ziqian SUN

### PR DESCRIPTION
**Pull request by sztsian**
Signed-off-by: Zamir SUN <sztsian@gmail.com>

### CODE REVIEW

**Comment by liushuyu** [comment]
It's okay to merge

**Comment by liushuyu** [comment]
Seems like GitHub is having difficulty synchronizing status with Travis CI.

**Comment by sztsian** [comment]
Am I grammatically wrong somewhere?

`$ curl -I https://aosc.io/people/~sztsian
HTTP/2 500 
server: nginx
date: Wed, 22 Feb 2017 08:56:48 GMT
content-type: text/html; charset=utf-8
content-length: 22
x-powered-by: Express
x-content-type-options: nosniff
content-security-policy: default-src 'self' wss: https: data: 'unsafe-inline' 'unsafe-eval'; img-src * data:; media-src * data:; object-src * data:;`

If so, I will learn to fix. If not, hope this can be fixed.

**Comment by MingcongBai** [comment]
Looking into it now.

**Comment by MingcongBai** [comment]
Fixed with 915f24a6a773e9c3b0145982b4d3fc2a79de680f. Pug won't be too happy if you mix spaces with indents.

**Pull request merged**
