### PR TITLE
Several merge-backs

### PR DESCRIPTION
**Pull request by liushuyu**
This change is [Reviewable](https://reviewable.io/reviews/aosc-dev/website-site-ng/80)

### CODE REVIEW

**Comment by MingcongBai** [comment]
@liushuyu

**Comment by LionNatsu** [comment]
I am not very clear about the testing system and the new mirror status monitor... Please feel free to merge when you think it is ready to merge.

BTW, @liushuyu, it maybe too long to be an issue... I will suggest that you may separate them into several branch by their functionalities next time.

(It says: "Pull requests that have a failing status can’t be merged on a phone." 🤣)

**Comment by liushuyu** [comment]
>I am not very clear about the testing system and the new mirror status monitor... Please feel free to merge when you think it is ready to merge.

I was thinking it was a false-positive, but now I saw the links in RSS feed are all `https://aosc.io/undefined`. I'll get to fix this.

So, see, this is the use of testing system, although my tests are not very good, but still be able to figure out some problems

**Comment by liushuyu** [comment]
Tests are passed despite the code check (need some kind of refactor to resolve the remaining problems), will merge this in 4 hours if there's no objections.

**Comment by liushuyu** [comment]
will merge this in 4 minutes if there's no objections.

**Comment by Yexiaoxing** [comment]
2 checks failed?

**Comment by liushuyu** [comment]
>2 checks failed? 

Only one now, it's the code style issue, can't be fixed unless a refactor is done.

**Comment by liushuyu** [comment]
Merged #80

**Pull request merged**
