### PR TITLE
cdn: use cdn in js and css

### PR DESCRIPTION
**Pull request by Yexiaoxing**

### CODE REVIEW

**Comment by liushuyu** [comment]
Emm... Are you sure to push to `master` branch first instead of pushing to `develop`?

**Comment by Yexiaoxing** [comment]
Well this is wrong ...

**Comment by Yexiaoxing** [comment]
For your information, here I use QingCloud's CDN service, with domain aosc-www.anthonos.org. Hope it will increase the speed of aosc.io.

**Comment by liushuyu** [comment]
Merged w/ Travis CI internal failure

**Comment by MingcongBai** [comment]
@liushuyu Please merge master.

**Pull request merged**
